---
# This playbook will install and configure an instance of rtf-master. The only requirement is to have ssh access to a server and sudo privileges. You will also need to have ansible installed locally. This play is run by `ansible-playbook ansible_playbook.yml --diff -b'
#

- hosts: rtfaws
  vars:
     rtf_root: "/srv/rtf"
  roles:
    - mysql_server
    - nginx
    - Rockabox.wsgi

  tasks:
    - name: Install dependencies
      apt: name="{{item}}" state=present
      with_items:
        - libgeos-dev
        - python-dev
        - python-mysqldb

    - name: Upgrade PIP
      become: yes
      shell: sudo pip install --upgrade pip

    - name: Pull latest code
      git: repo="https://github.com/cdahlhausen/rtf dest={{rtf_root}}"

    - name: Make virtualenv and activate
      shell: "echo TBD"

    - name: pip install -r requirements.txt
      shell: "echo TBD"

    - name: "python manage.py migrate"
      shell: "echo TBD"
