---
language: python
python: "2.7"
before_install:
  - ssh-keygen -t rsa -f $HOME/.ssh/id_rsa -N ""
  - touch $HOME/.ssh/authorized_keys
install:
  - pip install ansible==1.5.0
script:
  - echo localhost > inventory
  - ansible-playbook -i inventory test.yml --syntax-check
  - ansible-playbook -i inventory test.yml --connection=local --sudo
  - >
    ansible-playbook -i inventory test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
