---

- name: Create the Supervisor config file
  template: src=supervisor_config.j2
            dest=/etc/supervisor/conf.d/{{ wsgi_project_name }}.conf
            backup=yes
  notify:
    - reread supervisor config
    - update supervisor

- name: Create the supervisor log file
  command: touch {{ wsgi_log_dir }}supervisor.log
           creates={{ wsgi_log_dir }}supervisor.log
